name: Backend CI

on:
  push:

    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test:
    name: Run Tests

    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install
      
    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test